"""Optional offline FinRL policy adapter over Dwight's existing VWAP simulator.

No broker, downloader, credentials, or model promotion paths live here. An RL
action can only reject or retain a candidate already generated by VWAP. Episodes
advance between candidates, so gamma=1 preserves the undiscounted net-PnL target.
The unchanged historical next-bar fill assumptions are NOT broker fills.
"""
from dataclasses import asdict
from datetime import datetime
import hashlib
import json
import math
from pathlib import Path

from vwap_bot.engine import Bar, Config
from .context import PointInTimeContext
from .experiments import CandidateBot, FEATURE_NAMES, complete_sessions, _metrics

FINRL_REVISION = "e60e26e4870f00fbc704c6297edfd9d81816b3d3"
OBSERVATION_VERSION = "qqq-vwap-context-v1"


class _LongCandidateBot(CandidateBot):
    def _signal(self, b, prev):
        super()._signal(b, prev)
        if self.pending and self.pending["direction"] != 1:
            self.candidates[-1].update(taken=False, blocked_reason="long_only")
            self.pending = None


class DecisionReplay:
    """An episode of complete sessions, long-only QQQ; all decisions simulated.

    Observation: the ten existing causal features, simulated account state, a
    context-presence mask and age, followed by user-declared context features.
    Supplying context names makes a current snapshot mandatory for every take.
    Supplying no names creates the technical-only control arm.
    """
    def __init__(self, bars, config=Config(), context=None, *, synthetic=True):
        if type(synthetic) is not bool:
            raise ValueError("synthetic provenance must be explicit boolean")
        self.synthetic = synthetic
        self.bars = tuple(Bar(**asdict(bar)) for bar in bars)
        sessions, excluded = complete_sessions(self.bars)
        if not sessions or excluded:
            raise ValueError("RL replay requires nonempty complete 78-bar sessions; split before constructing episodes")
        if not isinstance(config, Config):
            raise ValueError("config must be a validated VWAP Config")
        self.config = config
        self.context = context if context is not None else PointInTimeContext((), [])
        if not isinstance(self.context, PointInTimeContext):
            raise ValueError("context must be PointInTimeContext")
        self.observation_names = (
            *FEATURE_NAMES, "equity_fraction", "daily_loss_count_fraction",
            "context_available", "context_age_days",
            *("context_" + name for name in self.context.feature_names),
        )
        if len(set(self.observation_names)) != len(self.observation_names):
            raise ValueError("context feature names collide with observation metadata")
        self.observation = [0.0] * len(self.observation_names)
        self.bot = None
        self.terminated = True

    def reset(self):
        self.bot = _LongCandidateBot(self.config)
        self.cursor = 0
        self.decisions = []
        self.terminated = False
        self._advance()
        return list(self.observation), dict(self.info)

    def _advance(self):
        while self.cursor < len(self.bars):
            self.bot.feed(self.bars[self.cursor])
            self.cursor += 1
            if self.bot.pending:
                candidate = self.bot.candidates[-1]
                at = datetime.fromisoformat(candidate["available_at"])
                self.snapshot = self.context.lookup(at)
                self.observation = [
                    *[float(candidate["features"][name]) for name in FEATURE_NAMES],
                    self.bot.equity / self.config.capital,
                    self.bot.losses / self.config.max_losses,
                    float(self.snapshot["available"]), self.snapshot["age_days"],
                    *self.snapshot["values"],
                ]
                if not all(math.isfinite(v) and abs(v) <= 1e30 for v in self.observation):
                    raise ValueError("observations must be finite and fit float32; preprocess context on training data only")
                self.info = {"available_at": candidate["available_at"],
                             "signal_time": candidate["signal_time"],
                             "context_available": self.snapshot["available"],
                             "research_only": True}
                return
        self.bot.finish()
        if any(t["exit_reason"] in {"end_of_data", "data_session_end"} for t in self.bot.trades):
            raise ValueError("unexpected forced boundary exit in RL episode")
        self.terminated = True
        self.observation = [0.0] * len(self.observation_names)
        self.info = {"research_only": True, "episode_complete": True}

    def step(self, action):
        if self.bot is None or self.terminated:
            raise ValueError("reset before stepping; episode is not active")
        if type(action) is not int or action not in (0, 1):
            raise ValueError("action must be 0 (skip) or 1 (take); sizing is not a policy action")
        before = self.bot.equity
        candidate = self.bot.candidates[-1]
        context_missing = bool(self.context.feature_names) and not self.snapshot["available"]
        take = action == 1 and not context_missing
        reason = "context_unavailable" if action == 1 and context_missing else "take" if take else "policy_skip"
        self.decisions.append({
            **self.info, "action_requested": action, "taken": take, "reason": reason,
            "observation": list(self.observation),
            "context_source": self.snapshot["source"],
            "context_available_at": self.snapshot["available_at"],
            "context_expires_at": self.snapshot["expires_at"],
        })
        candidate["taken"] = take
        if not take:
            self.bot.pending = None
        self._advance()
        reward = (self.bot.equity - before) / self.config.capital
        return list(self.observation), reward, self.terminated, False, {**self.info, "previous_action": reason}

    def provenance(self):
        def digest(value):
            return hashlib.sha256(json.dumps(value, sort_keys=True, allow_nan=False).encode()).hexdigest()
        return {
            "symbol": "QQQ", "long_only": True, "synthetic": self.synthetic,
            "observation_version": OBSERVATION_VERSION,
            "observation_names": list(self.observation_names), "strategy": asdict(self.config),
            "bars_sha256": digest([{**asdict(b), "timestamp": b.timestamp.isoformat()} for b in self.bars]),
            "context_sha256": digest(self.context.to_dict()),
            "start": self.bars[0].timestamp.isoformat(), "end": self.bars[-1].timestamp.isoformat(),
            "bars": len(self.bars), "requires_context": bool(self.context.feature_names),
        }

    def report(self):
        if self.bot is None or not self.terminated:
            raise ValueError("report requires a completed episode")
        return {
            **self.provenance(), "mode": "offline_research", "promotion_eligible": False,
            "metrics": _metrics(self.bot), "decisions": self.decisions,
            "trades": self.bot.trades, "equity": self.bot.curve,
            "context_coverage": sum(d["context_available"] for d in self.decisions) / len(self.decisions)
                                if self.decisions and self.context.feature_names else None,
            "limitations": ["Historical simulated fills, not broker results",
                            "No fundamental data feed or publication-vintage verification",
                            "Only full regular sessions; early closes unsupported",
                            "Event-time policy steps; use gamma=1 for net-PnL reward",
                            "No walk-forward selection, statistical edge claim, or runtime promotion"],
        }


def _action(value):
    # SB3 predict emits a numpy scalar or one-element array for this environment.
    if hasattr(value, "item"):
        value = value.item()
    if type(value) is not int or value not in (0, 1):
        raise ValueError("policy returned an invalid skip/take action")
    return value


def make_gym_env(replay):
    """Lazy Gymnasium adapter; neither Gymnasium nor FinRL is a core dependency."""
    try:
        import gymnasium as gym
        import numpy as np
    except ImportError as exc:
        raise RuntimeError("install the optional rl-env extra in an isolated research environment") from exc

    class VWAPEnv(gym.Env):
        metadata = {"render_modes": []}

        def __init__(self):
            self.replay = replay
            self.observation_space = gym.spaces.Box(-1e30, 1e30, shape=(len(replay.observation_names),), dtype=np.float32)
            self.action_space = gym.spaces.Discrete(2)

        def reset(self, *, seed=None, options=None):
            super().reset(seed=seed)
            observation, info = self.replay.reset()
            if self.replay.terminated:
                raise ValueError("episode has no eligible long VWAP candidates")
            return np.asarray(observation, dtype=np.float32), info

        def step(self, action):
            observation, reward, terminated, truncated, info = self.replay.step(_action(action))
            return np.asarray(observation, dtype=np.float32), reward, terminated, truncated, info

    return VWAPEnv()


def evaluate_policy(replay, policy):
    """Evaluate predict(observation, deterministic=True) on caller-held-out bars."""
    env = make_gym_env(replay)
    observation, _ = env.reset()
    while True:
        action, _ = policy.predict(observation, deterministic=True)
        observation, _, terminated, truncated, _ = env.step(action)
        if terminated or truncated:
            break
    return replay.report()


def train_ppo(env, output: Path, *, total_timesteps=2048, seed=0):
    """Optional FinRL training seam, requiring a separately validated install.

    Pass training-partition bars ONLY. This does not tune, evaluate or promote a
    policy. Outputs are local SB3 artifacts, not Dwight JSON release models.
    """
    if type(total_timesteps) is not int or total_timesteps < 64 or type(seed) is not int or seed < 0:
        raise ValueError("training requires >=64 timesteps and a nonnegative integer seed")
    if not isinstance(getattr(env, "replay", None), DecisionReplay):
        raise ValueError("training requires Dwight's VWAP Gymnasium environment")
    output = Path(output)
    if output.exists():
        raise ValueError("choose a new training output directory")
    try:
        from finrl.agents.stablebaselines3.models import DRLAgent
    except ImportError as exc:
        raise RuntimeError("FinRL training dependencies are not installed/compatible; see docs/finrl-research.md") from exc
    from importlib.metadata import version
    env.reset(seed=seed)
    output.mkdir(parents=True, exist_ok=False)
    try:
        agent = DRLAgent(env)
        model = agent.get_model("ppo", policy="MlpPolicy", seed=seed, verbose=0,
                                model_kwargs={"device": "cpu", "gamma": 1.0, "n_steps": 64, "batch_size": 64})
        model = agent.train_model(model, tb_log_name="dwight_vwap", total_timesteps=total_timesteps)
        model.save(str(output / "policy.zip"))
        report = {
            **env.replay.provenance(), "schema_version": 1, "kind": "finrl_ppo_research",
            "promotion_eligible": False, "seed": seed, "requested_timesteps": total_timesteps,
            "actual_timesteps": int(model.num_timesteps),
            "gamma": 1.0, "reviewed_finrl_revision": FINRL_REVISION,
            "installed_finrl_version": version("finrl"),
            "stable_baselines3_version": version("stable-baselines3"),
            "policy_sha256": hashlib.sha256((output / "policy.zip").read_bytes()).hexdigest(),
            "evaluation": "not_performed", "market_data_provenance": "caller_supplied_unverified",
        }
        (output / "training.json").write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")
        return model, report
    except Exception as exc:
        (output / "failed.json").write_text(json.dumps({"error_type": type(exc).__name__}) + "\n")
        raise
